### PR TITLE
Fix: make data-structure returned from `/list-case-sets` compliant 

### PR DESCRIPTION
**Pull request by neopostmodern**
...with swagger spec

(the endpoint seems to be not used anywhere in this repo, so it should be non-breaking)

### CODE REVIEW

**Comment by perov-babylon** [comment]
@neopostmodern, thank you very much. Could you run `make format` (using the shell/console in the root folder of the repo in the virtual environment if you use it) to satisfy `make lint` for repo's formatting requirements, please. It will replace the `'` quotes by `"` quotes.

**Comment by perov-babylon** [comment]
Good catch!

**Comment by neopostmodern** [comment]
I've fixed another bug along the way, it was including the `repots_*.db` as case sets

**Comment by perov-babylon** [comment]
Thank you very much. Merging into this repo branch `improve-list-case-sets`. Will create a PR to merge to `master` from there.

**Comment by perov-babylon** [comment]
Will merge into the master in https://github.com/babylonhealth/itu_who_2019_symptom_assessment_mmv_benchmark/pull/21.

**Pull request merged**
